name: 'Deploy Lodex'
on:
  release:
      types: [published]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out from Git
        uses: actions/checkout@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
            username: ${{ secrets.DOCKER_LOGIN }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run deploy script
        shell: bash
        run: |
            echo ${{ secrets.DOCKER_LOGIN }}
            chmod +x ${GITHUB_WORKSPACE}/.github/workflows/deploy.sh
            ${GITHUB_WORKSPACE}/.github/workflows/deploy.sh
