name: Lodex CI
on:
  push:
    branches: [ master ]
    tags:        
      - '*'
  pull_request:
    branches: [ master ]
     

jobs:
  test-unit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install LODEX
      run: make install

    - name: Start Unit Tests
      run: make test-unit

  test-api-e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install LODEX
      run: make install

    - name: Start API E2E Tests
      run: make test-api-e2e

  test-e2e:
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install LODEX
      run: make install

    - name: Start E2E Tests
      run: make test-e2e

  deploy: 
    steps:
    - name: Check out from Git
      uses: actions/checkout@v1

    - name: Check if Git tag exists
      run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"

    - name: Runs only if Git tag exists
      run: echo"This runs because Git tag points at HEAD ..."
      if: env.HEAD_TAG != ''
