name: Lodex CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
     
jobs:
  test-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        # See https://github.com/nodejs/Release
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run Tests Unit
        run: make install

      - run: make test-unit

  test-api-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run API E2E Tests
        run: make install

      - run: make test-api-e2e

  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install

      - name: Run E2E Tests
        run: make test-e2e

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
