name: Lodex CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        # See https://github.com/nodejs/Release
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Those three lines do the same things as "make install" and "make test-unit" but without a docker container
      - run: make copy-conf
      - run: npm ci

      - run: npm run test:unit

  test-api-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Those two lines do the same things as "make install" but without a docker container
      - run: make copy-conf
      - run: npm ci

      - run: make test-api-e2e

  build-e2e-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Those two lines do the same things as "make install" but without a docker container
      - run: make copy-conf
      - run: npm ci

      - run: docker compose -f docker-compose.spec.yml build

      - run: docker save --output lodex-api.tar lodex-api

      - uses: actions/upload-artifact@v3
        with:
          name: lodex-api
          path: /tmp/lodex-api.tar

  test-e2e:
    runs-on: ubuntu-latest
    needs: build-e2e-image
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [ 12.x ]
        test-phase: [ 'phase:one', 'phase:two', 'phase:three', 'phase:four' ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Those two lines do the same things as "make install" but without a docker container
      - run: make copy-conf
      - run: npm ci

      - uses: actions/download-artifact@v3
        with:
          name: lodex-api
          path: /tmp

      - run: docker load --input /tmp/lodex-api.tar

      - run: make test-e2e-start-dockers

      - run: ./bin/wait-for -t 60 localhost:3000
      - run: npm run test:e2e:${{ matrix.test-phase }}

      - run: make test-e2e-stop-dockers

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
